name: DEV

on:
  pull_request:
    branches: ['master']
    types: ['closed']
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t vrde-api:dev .
          docker tag vrde-api:dev "$REGISTRY"/vrde-api:dev

      - name: Push Docker Image
        run: docker push "$REGISTRY"/vrde-api:dev
